apiVersion: apps/v1
kind: Deployment
metadata:
  name: calico-kube-controllers
  labels:
    k8s-app: calico-kube-controllers
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: calico-kube-controllers
  template:
    metadata:
      labels:
        k8s-app: calico-kube-controllers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: calico-kube-controllers
      containers:
      - name: calico-kube-controllers
        image: calico/kube-controllers:v3.6.1
        env:
        - name: ENABLED_CONTROLLERS
          value: node
        - name: DATASTORE_TYPE
          value: kubernetes
        readinessProbe:
          exec:
            command:
            - /usr/bin/check-status
            - -r
