# Copyright 2020 SIGHUP s.r.l
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

namespace: kube-system

images:
  - name: calico/kube-controllers
    newTag: v3.16.1
  - name: calico/cni
    newTag: v3.16.1
  - name: calico/pod2daemon-flexvol
    newTag: v3.16.1
  - name: calico/node
    newTag: v3.16.1

resources:
- config.yml
- crd.yml
- deploy.yml
- ds.yml
- rbac.yml
- sm.yml
